name: NVTravels
favicon: null
layout_spectrum: 0.7005243441089988
typography_spectrum: 0.7553281188011169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2548461176920682
  lightness: 0.8477769289165735
  saturation: 0.245472124312073
  rhythmicContrast: 0.6756982002407312
purpose: []
